services:
  - type: web
    name: videochat-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: CORS_ORIGIN
        value: https://video-chat-client-9k8a.onrender.com

  - type: static
    name: videochat-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
