services:
  - type: web
    name: videochat-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js

  - type: static
    name: videochat-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
